server:
  port: 8082
  servlet:
    context-path: /api

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  rabbitmq:
    hostname: ${HOSTNAME_RABBITMQ}
    username: ${USER_RABBITMQ}
    password: ${PASS_RABBITMQ}
    port: 5672
    exchange: payment.exchange
    routingkey: payment.routingkey
    queue: payment.queue

  datasource:
    url: ${DB_URL_PAYM}
    username: ${DB_USER_PAYM}
    password: ${DB_PASS_PAYM}
  jpa.show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
